apiVersion: v1
kind: Namespace
metadata:
  name: testing

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: testing-middleware-compress
  namespace: testing
spec:
  compress: {}
