apiVersion: v1
kind: Namespace
metadata:
  name: testing

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: testing-middleware-headers
  namespace: testing
spec:
  headers:
    test-header:
      - "test-value"
    other-header:
      - "other-value"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: testing-middleware-headers-cors
  namespace: testing
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
