[package]
name = "htpasswd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.118"
bcrypt = "0.10"
rust-crypto = "0.2"
pwhash = "1.0"
base64 = { version = "0.13.0" }
