kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tunneload-controller

rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - traefik.containo.us
    resources:
      - middlewares
      - ingressroutes
      - traefikservices
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
      - serverstransports
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tunneload-controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tunneload-controller
subjects:
  - kind: ServiceAccount
    name: tunneload-controller
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-tunneload
  labels:
    app: http-tunneload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-tunneload
  template:
    metadata:
      labels:
        app: http-tunneload
    spec:
      serviceAccountName: tunneload-controller
      containers:
        - name: http-tunneload
          image: lol3r/tunneload:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: RUST_LOG
              value: debug
            - name: KEY_FILE
              value: /mnt/key
            - name: SERVER_ADDR
              value: "[server-ip]"
            - name: SERVER_PORT
              value: "8081"
            - name: K8S_UTIME
              value: "1m"
          volumeMounts:
            - name: "key-volume"
              mountPath: "/mnt/key"
              subPath: "key"
      volumes:
        - name: "key-volume"
          secret:
            secretName: "tunneler-secret"

---
apiVersion: v1
kind: Secret
metadata:
  name: tunneler-secret
type: Opaque
data:
  key: TVk0aXFYSmlQSytQaEFmKzZnbnRDR04xeGQ1bFZQTUs4aEhtWU0xT1RuRGc2aDdxOFEvaEVHUzNTcmNmR1NzeDg3cCtSK3FGdkc3d3lwblhwbGdpRGF5SUNpdnB5SU13NVJSemxUMVpCNlJkQ3F4WDIrRzFlMjZjU3RFdzdZTm1JRGdZZGl2WGQwZ0Q0WUJUR0VsemhaQlNsV3Q5a2FLaVdWeWtjaEZxOFdjPQ==
