---
kind: Service
apiVersion: v1
metadata:
  name: test-service
  namespace: testing
spec:
  ports:
    - name: test
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 0

---
kind: Endpoints
apiVersion: v1
metadata:
  name: test-service
subsets:
  - addresses:
      - ip: "127.0.0.1"
    ports:
      - port: 80
        name: test
