name: Rust Verification
on: [push]
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: icepuma/rust-action@master
        with:
          args: cargo clippy
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: icepuma/rust-action@master
        with:
          args: cargo test
